name: Generate Snake Animation

on:
  schedule:               # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:      # Allow manual trigger
  push:
    branches:
      - main              # Trigger on push to main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write     # ✅ Required to push to output branch

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ This is automatically available in GitHub Actions
